[IMP] make relation selection field
onesteinbv/addons-onestein pull request #47
Opened 2018-05-01 11:32 UTC by CasVissers

Relation can be a selection field creating cleaner relation information.

2018-05-01 11:40 UTC, espo-tony requested changes
Selection field, here, would surely give some advantage in usage, restricting the number of possible options to a small and well definite set.
The drawback is that it makes this field much less flexible, avoiding the possibility to set an unexpected relationship.
I think that, for this case, pros overcome cons, but I'd also like to have a confirm that different relationships than those listed in this PR make no sense in the context of this module.

2018-05-01 11:40 UTC, espo-tony commented on hr_employee_related/models/hr_employee_related.py
> +        default='depreciate')
The default value doesn't appear to be in the option list.

2018-05-01 11:40 UTC, espo-tony approved these changes

2018-05-01 12:00 UTC, pankk commented
Judging from the module's description, this module can be used to store ICE (in case of emergency) information. In that case it would be useful to also have, for example 'caretaker' in the selection. Since there may be other officially designated relations which can serve as ICE contacts, I think it would be prudent to consider adding 'other' to the selection as well.

2018-05-04 14:51 UTC, CasVissers commented
I agree, added caretaker & other.

2018-10-26 11:41 UTC, CasVissers commented
an update here?

2018-10-26 11:54 UTC, merged