8.0 [IMP] account_cost_spread improvements
onesteinbv/addons-onestein pull request #49
Opened 2018-05-18 16:43 UTC by thomaspaulb

* Auto reconcile move lines
* Add menus
* Alternative start date
* Tests

2018-05-18 16:45 UTC, thomaspaulb commented
@gfcapalbo @hbrunn Combines #35 #36 and some other improvements on `account_cost_spread`

2018-05-19 09:30 UTC, hbrunn commented
thanks @thomaspaulb - @gfcapalbo can you close your versions of this?

2018-06-16 21:46 UTC, thomaspaulb commented
@astirpe Two questions for you:

1. According to [this code](https://github.com/onesteinbv/addons-onestein/blob/10.0/account_cost_spread/models/account_invoice.py#L16) in the `10.0` version as well as this one, the spread lines are always already created for each invoice line when the invoice is validated. However, I would think this is overly active behaviour - only relatively few invoice lines on few invoices would need spreading, as activated by the spread button. Doesn't the current behaviour clutter the database with unused spread lines?
2. Any chance for a review? We should perhaps take the good things from this PR and then incorporate them in a backport from the 10.0 version.

2018-06-18 07:28 UTC, astirpe commented
@thomaspaulb  thanks for the job you are doing!

1. yes indeed we should avoid the creation of unused spread lines;  this is for us a low priority task, if you have proposals they will be very well accepted!

2. version 11.0 is the one with the most advanced code, we should take in consideration that one for the backporting (I think Holger already did it). I will make a proper review as soon as I have enough time for it, I hope soon!

Thanks again!

2018-06-19 08:38 UTC, astirpe requested changes
Thanks for this.
You may also want to add yourself in the contributors list.

We could also think of proposing this module to OCA one day...

2018-06-19 08:38 UTC, astirpe commented on account_cost_spread/models/account_invoice_line.py
> -            fy = DummyFy(
Since you do not make use of `DummyFy()` anymore, you can safely remove its definition: https://github.com/sunflowerit/addons-onestein/blob/462bcc7081e4d9d40ab28300be51fdf65d305ca7/account_cost_spread/models/account_invoice_line.py#L14-L17

2018-06-19 08:38 UTC, astirpe commented on account_cost_spread/models/account_invoice_line.py
> +    def _compute_spread_board(self):
I see you backported the computation mechanism from the 11.0 version, that is great! Much more understandable and maintainable code.
The README should be updated accordingly, since the code is now based on the Odoo SA `account_assets` module (and not anymore on the `account_assets_management` module):

```
The computation code in this module is based on
the Assets Management module by Odoo SA.
```

2018-06-19 08:38 UTC, astirpe commented on account_cost_spread/tests/test_account_cost_spread.py
> +from datetime import date
This date import seems not used anymore

2018-06-19 08:38 UTC, astirpe commented on account_cost_spread/models/account_invoice_spread_line.py
> +        #  currency_obj = self.env['res.currency']
We can just remove this line

2018-06-19 08:38 UTC, astirpe commented on account_cost_spread/models/account_invoice_spread_line.py
> +    def _check_init_entry(self):
After backporting the spread logic from V11, I think that the `init_entry` field is not necessary anymore and could be removed, as well as this `_check_init_entry()` method. Could you check?

Same discourse of the field `type = fields.Selection()`.

2018-06-19 08:38 UTC, astirpe commented on account_cost_spread/models/account_invoice_line.py
> -            fy_date_start = datetime.strptime(
`datetime` is not used anymore, you can remove it from the imports

2018-06-19 16:47 UTC, thomaspaulb commented
@astirpe Thanks for the review! I think submitting the `11.0` version to OCA will be a great idea, it's not that much work and perhaps something will come of it.

2018-06-19 16:53 UTC, astirpe requested changes

2018-06-19 16:53 UTC, astirpe commented on account_cost_spread/__openerp__.py
> +    'author': 'Onestein BV',
Please don't change the author

2018-06-20 07:32 UTC, astirpe requested changes

2018-06-20 07:32 UTC, astirpe commented on account_cost_spread/models/account_invoice_spread_line.py
> +        """ Check existing move """
self.ensure_one()

2018-06-21 08:22 UTC, merged

2018-06-25 17:32 UTC, astirpe commented
In https://github.com/onesteinbv/addons-onestein/commit/c715a461b66ca004401274a2ca75f53bb9ad01cd I just pushed a fix for V11 to avoid the creation of unused spread lines.

2018-10-23 08:35 UTC, astirpe commented
I'm proposing the V11 of this module to be hosted in OCA. Here is the PR https://github.com/OCA/account-financial-tools/pull/715. I renamed the module to `account_spread_cost_revenue`. ... In case you are interested ... :smiley: